language: ruby

cache: bundler

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

env:
  - DB=sqlite
  - DB=postgresql
  - DB=mysql

services:
  - mysql
addons:
  postgresql: "9.3"

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_5_1.gemfile

